feedback table header - a11y
RedTurtle/volto-feedback pull request #1
Opened 2024-01-17 15:49 UTC by Wagner3UB

- <Button> added to define a real button
- Focus set on css (bootstrap color used)
- aria-description added to describe the possible action (not aria-label, my objective wasn't changing the label, but describe the action + the original button text)
- useRef() used to re-position the focus on the button clicked after app re-rendering

2024-01-18 08:18 UTC, giuliaghisini requested changes

2024-01-18 08:18 UTC, giuliaghisini commented on locales/it/LC_MESSAGES/volto.po
> +msgstr "Ordina per: Clicca per disporre gli elementi in questa colonna"
Metterei: 
"Ordina per: Clicca per ordinare gli elementi in questa colonna"

2024-01-18 09:23 UTC, giuliaghisini approved these changes

2024-02-02 08:02 UTC, Wagner3UB commented
@pnicolli Vuoi fare un check?

2024-02-02 08:50 UTC, pnicolli requested changes

2024-02-02 08:50 UTC, pnicolli commented on locales/it/LC_MESSAGES/volto.po
> +msgstr "Ordina per: Clicca per ordinare gli elementi in questa colonna"
Manca `{sort}` nella msgstr

2024-02-02 08:50 UTC, pnicolli commented on src/components/manage/VFPanel/VFPanel.jsx
> +                              { sort: sort_on === 'vote' ? sort_order : '' },
Anche il `sort_order` che passi come parametro per la traduzione immagino vada tradotto, dato che altrimenti sarebbe per tutti una stringa `ascending` o `descending`

2024-02-16 09:10 UTC, Wagner3UB commented
@pnicolli Possiamo mergiare questa?

2024-02-16 09:25 UTC, pnicolli commented
@Wagner3UB ci stavo giusto riguardando ieri prima di staccare. Deve sparire di nuovo la modifica al file yarn.lock, che è tornata, poi mergiamo.

2024-02-16 09:28 UTC, Wagner3UB commented
> @Wagner3UB ci stavo giusto riguardando ieri prima di staccare. Deve sparire di nuovo la modifica al file yarn.lock, che è tornata, poi mergiamo.

Avevo fatto prima di chiederti, no? Non vedo più conflitti

2024-02-16 11:53 UTC, pnicolli requested changes

2024-02-16 11:53 UTC, pnicolli commented on src/components/manage/VFPanel/VFPanel.jsx
> +import React, { useState, useEffect, useMemo, useRef } from 'react';
Togli questo useRef anche da qui se non serve più

2024-02-16 11:55 UTC, pnicolli approved these changes

2024-02-16 11:56 UTC, merged